# Generated by Django 4.1 on 2022-09-05 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0004_alter_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coins',
            name='profile',
        ),
        migrations.AddField(
            model_name='coins',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/products/product.png', null=True, upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, default='images/profiles/profile.png', null=True, upload_to='images/profiles'),
        ),
    ]
