# Generated by Django 4.1 on 2022-09-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_remove_coins_profile_coins_user_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='btc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='coins',
            name='eth',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
