# Generated by Django 4.1 on 2022-09-07 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_coins_btc_alter_coins_eth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='coin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.coins'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
