# Generated by Django 4.1 on 2022-09-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_remove_ticket_transaction_id_order_coin_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coins',
            name='eth',
        ),
    ]
